"""Web build entry point (copied into the web bundle as ``web_boot.py``).

The page (index.html) compiles this file with ``/game/web_boot.py`` as its
filename and awaits ``main()``, so the runtime resolves the project root the
same way a desktop ``main.py`` does (see ``Game._init_game``).

The engine inside the bundle is a copy: its ``api/core/game.py`` is patched by
the build to add ``Game.run_async()`` (an asyncio loop that never blocks the
browser tab). The installed engine is not touched.

This module is only used by the Web build; the desktop build keeps using the
project's own main.py.

When the project uses physics, ``main()`` first loads the pymunk wheel the
build placed next to the page (or, without that wheel, installs the package
from PyPI), so the browser can simulate falling, colliding objects.
"""

import asyncio
import importlib.util
import os
import sys
from pathlib import Path

#: The bundle root: the folder this file (and the project) was unpacked into.
PROJECT_ROOT = Path(__file__).resolve().parent.as_posix()
#: The project's entry file, generated by the editor like in the desktop build.
MAIN_FILE_NAME = 'main.py'


def _load_project_main():
    """Load the project's main.py directly from the bundle root.

    The file is loaded by path on purpose: no import system search for a
    module named "main" (which depends on sys.path and the current folder in
the browser) is involved.
    """
    main_path = Path(PROJECT_ROOT) / MAIN_FILE_NAME
    if not main_path.is_file():
        found = ', '.join(sorted(path.name for path in Path(PROJECT_ROOT).iterdir()))
        raise RuntimeError(
            '{} is missing from the game bundle (found: {}). Build the web app '
            'again and upload both index.html and game.zip. / 游戏包中缺少 {}（实际包含：{}），'
            '请重新打包网页版并重新上传 index.html 与 game.zip。'.format(
                MAIN_FILE_NAME, found, MAIN_FILE_NAME, found))

    spec = importlib.util.spec_from_file_location('main', main_path.as_posix())
    project_main = importlib.util.module_from_spec(spec)
    sys.modules['main'] = project_main
    spec.loader.exec_module(project_main)
    return project_main


def _find_game_class(project_main):
    """The project's Game class, whatever the protection did to its name.

    The build obfuscates the project code like the desktop build does and that
    can rename the class, so the boot does not rely on the name ``Game``: the
    first subclass of the engine's Game inside main.py wins.
    """
    import pygamestudio as studio

    game_class = getattr(project_main, 'Game', None)
    if isinstance(game_class, type) and issubclass(game_class, studio.Game):
        return game_class

    for value in vars(project_main).values():
        if isinstance(value, type) and issubclass(value, studio.Game) and value is not studio.Game:
            return value

    raise RuntimeError(
        'main.py does not define a game class (a subclass of studio.Game). / '
        'main.py 中没有定义游戏类（studio.Game 的子类）。')


def _notify_page(hook_name, *args):
    """Call a hook the page installed (no-op outside the browser)."""
    try:
        import js

        callback = getattr(js, hook_name, None)
        if callback is not None:
            callback(*args)
    except Exception:
        pass


async def _prepare_physics(install_source):
    """Make pymunk available when the project uses physics ('' = skip).

    The build ships the Pyodide wheel of pymunk next to index.html and it is
    loaded straight through ``loadPackage`` - no package manager involved -
    with its only dependency (cffi) loaded from the Pyodide distribution
    first. Without that wheel the fallback installs the package from PyPI
    through micropip, which is part of the distribution but has to be loaded
    before it can be used.
    """
    if not install_source:
        return
    try:
        import pyodide_js

        await pyodide_js.loadPackage('cffi')

        if install_source.endswith('.whl'):
            if '://' not in install_source:
                from js import URL, location
                install_source = URL.new(install_source, location.href).href
            await pyodide_js.loadPackage(install_source)
            return

        # No shipped wheel: the plain package name is fetched from PyPI.
        await pyodide_js.loadPackage('micropip')

        import micropip

        await micropip.install(install_source)
    except Exception as error:
        # The game still starts: the engine imports pymunk lazily and simply
        # skips the simulation when that import fails.
        print('[pygamestudio] physics support could not be installed: {}'.format(error), file=sys.stderr)


async def main():
    """Import the project's main.py and run its Game loop until it quits."""
    os.environ['PROJECT_PATH'] = PROJECT_ROOT
    os.environ['__PYGAMESTUDIO_PROJECT_PATH'] = PROJECT_ROOT
    os.chdir(PROJECT_ROOT)
    if PROJECT_ROOT not in sys.path:
        sys.path.insert(0, PROJECT_ROOT)

    await _prepare_physics('__PYGS_PYMUNK_SOURCE__')
    _notify_page('__pygsProgress', 97)

    project_main = _load_project_main()
    game = _find_game_class(project_main)()
    # The page keeps its loading bar up to this point: from here on the game
    # loop itself is running.
    _notify_page('__pygsGameStarted')
    await game.run_async()


if __name__ == '__main__':
    asyncio.run(main())
