from .button import ObjectButton
from .canvas import ObjectCanvas
from .ellipse import ObjectEllipse
from .frame_sequence import ObjectFrameSequence
from .image import ObjectImage
from .line import ObjectLine
from .particle import ObjectParticle
from .polygon import ObjectPolygon
from .rect import ObjectRect
from .text import ObjectText
from .type import *